apiVersion: v1
kind: Pod
metadata:
  name: jobgeneratorpy
  labels:
    name: jobgeneratorpy
spec:
  serviceAccountName: kube-client
  restartPolicy: Never
  containers:
    - name: generator
      image: 0gis0/k8spythonclient
      imagePullPolicy: Always
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"